#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
define('DIR', __DIR__);
date_default_timezone_set('PRC');

use Symfony\Component\Console\Application;
use App\Console\Kernel;
use Dotenv\Dotenv;
use Dotenv\Environment\Adapter\EnvConstAdapter;
use Dotenv\Environment\Adapter\PutenvAdapter;
use Dotenv\Environment\DotenvFactory;


$factory = new DotenvFactory([
    new EnvConstAdapter(),
    new PutenvAdapter()
]);

$dotenv = Dotenv::create(__DIR__, null, $factory);
$dotenv->overload();

$application = new Application();

// 注册编写的命令
$kernel = new Kernel();
foreach ($kernel->commands as $command) {
    $application->add(new $command());
}
$application->run();